spring:
  application:
    name: monitoring-service
server:
  port: 8090
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8585/eureka/

  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: false

turbine:
  clusterNameExpression: new String("default")
  appConfig: FIRST-SERVICE,SECOND-SERVICE
  combineHostPort: true
